#!/usr/bin/env bash
set -euo pipefail

if [ "${DEBUG:-false}" == true ]; then set -x; fi

usage() {
cat<<EOF
$0 <command> [args]

Commands:
add [suffix]
  Generate and add a new item

rm|delete [uuid|index]
  Remove a specific record by ID or index.
  If neither UUID or index is specified, the first item is removed.

ls|list
  List all items

${1:-}
EOF
exit 1
}


URL=http://localhost:8080/v1/facilityvisit/facilityvisits

main() {
  local command="${1:-none}"
  shift || true
  case $command in
    a*) add $@;;
    l*) listAll $@;;
    d*|rm) delete $@;;
    none) usage "No command specified";;
    *) usage "Unkown command: $command";;
  esac
}

listAll() {
  local query
  if [ -n "${1:-}" ]
  then
    query="?$1"
  fi
  if [ -t 1 ]
  then
    curl -s ${URL}${query:-} | jq .
  else
    curl -s ${URL}${query:-}
  fi
}

add() {
  local n=${1:-}
  if [ -z "${n:-}" ]
  then
    n=$(( 1 + $(listAll | jq .totalItems) ))
  fi
  local json
  json=$(jq --null-input \
    --arg fid "fid-$n" \
    --arg type "type-$n" \
    --arg icn "icn-$n" \
    --arg vn "$(date --iso-8601=seconds)" \
    '{"facilityId":$fid,"type":$type,"visitorIcn":$icn,"visitedAt":$vn}')
  curl -s \
    -HContent-Type:application/json \
    -d "$json" \
    $URL
}

delete() {
  local id=${1:-0}
  if [[ "${id}" =~ ^[0-9]+$ ]]
  then
    local realId
    realId=$(listAll | jq -r ".items[$id].id")
    if [ "${realId}" == "null" ]
    then
      echo "No item at index $id"
      exit 1
    fi
    id=$realId
  fi
  curl -s \
    -X DELETE \
    $URL/$id
}

main $@
