spring:
  datasource:
    url: jdbc:postgresql://postgres1:5432/facilityvisit
    username: facilityvisit_service
    password: also-not-the-service-password
    hikari:
      jdbc-url: jdbc:postgresql://postgres1:5432/facilityvisit
      username: facilityvisit_service
      password: also-not-the-service-password
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: "kafka:9092"

provider: mpi
mpi:
  ssl-enabled: false
  url: "http://mock-mpi:9090/psim_webservice/IdMWebService"
  wsdl-location: "http://mock-mpi:9090/psim_webservice/IdMWebService/idmWebService.wsdl"
  keystore-path: "/opt/va/mock-mpi-client.keystore"
  keystore-password: "password123"
  key-alias: "mock-mpi-client"
  truststore-path: "/opt/va/mock-mpi-client.truststore"
  truststore-password: "password123"
  user-id: LIGHTHOUSE
  integration-process-id: 666LHSE
  as-agent-id: 666LHSG

opentracing:
  zipkin:
    enabled: true
    http-sender.baseUrl: http://jaeger:9411

logging:
  level:
    org.springframework.jdbc.core: INFO # DEBUG
    org.springframework.jdbc.core.JdbcTemplate: INFO # DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: INFO # TRACE
    org.hibernate.SQL: INFO # DEBUG
    org.type.descriptor.sql.BasicBinder: INFO # TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: INFO # TRACE
