version: '3.9'

networks:
  internal:
  external:

volumes:
  pgdata:

services:
  postgres1:
    image: postgres
    hostname: postgres1
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: facilityvisit_flyway
      POSTGRES_PASSWORD: not-the-password
      POSTGRES_DB: facilityvisit
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal
      - external

  db-init:
    image: va/lighthouse-di-starterkit-java-flyway:latest
# NOTE: These are the defaults from the flyway.conf   uncomment to override, esp for <secret-service-name> passwords
#    environment:
#      FLYWAY_URL: jdbc:postgresql://postgres1:5432/facilityvisit?user=facilityvisit_flyway&password=not-the-password
#      FLYWAY_PLACEHOLDERS_USERNAME: facilityvisit_user
#      FLYWAY_PLACEHOLDERS_SERVICENAME: facilityvisit_service
#      FLYWAY_PLACEHOLDERS_ADMINNAME: facilityvisit_admin
#      FLYWAY_PLACEHOLDERS_DBNAME: facilityvisit
#      FLYWAY_PLACEHOLDERS_SCHEMANAME: facilityvisit
#      FLYWAY_PLACEHOLDERS_USERPASSWORD: also-not-the-user-password
#      FLYWAY_PLACEHOLDERS_SERVICEPASSWORD: also-not-the-service-password
#      FLYWAY_PLACEHOLDERS_ADMINPASSWORD: also-not-the-admin-password
    depends_on:
      - postgres1
    networks:
      - internal

