version: '3.9'

networks:
  internal:
  external:

volumes:
  pgdata:

services:
  mock-mpi:
    image: vasdvp/lighthouse-mock-mpi:1.0.9
    hostname: "mock-mpi"
    expose:
      - "9090"
    ports:
      - "9090:9090"
    environment:
      SSL_ENABLE_CLIENT: "false"
      SSL_USE_TRUST_STORE: "false"
      SECURITY_REQUIRE_SSL: "false"
      SERVER_SSL_ENABLED: "false"
      SERVER_SSL_KEY_STORE_TYPE: "JKS"
      SERVER_SSL_KEY_STORE: "/opt/va/mock-mpi-server.keystore"
      SERVER_SSL_KEY_STORE_PASSWORD: "password123"
      SERVER_SSL_KEY_ALIAS: "mock-mpi-server"
      PATIENT_VISTA_SITE_DETAILS: "/opt/va/vista-sites.json"
    volumes:
      - ${PWD}/app/src/docker/vista-sites.json:/opt/va/vista-sites.json
      - ${PWD}/app/src/docker/mock-mpi-server.keystore:/opt/va/mock-mpi-server.keystore
      - ${PWD}/app/src/docker/mock-mpi-server.truststore:/opt/va/mock-mpi-server.truststore
    networks:
      - internal
      - external

  opa:
    image: openpolicyagent/opa
    hostname: opa
    expose:
      - "8181"
    ports:
      - "8181:8181"
    command:
      - run
      - --server
      - --log-level
      - debug
    networks:
      - internal
      - external

  postgres1:
    image: postgres
    hostname: postgres1
    expose:
      - "5432"
    environment:
      POSTGRES_USER: facilityvisit_flyway
      POSTGRES_PASSWORD: not-the-password
      POSTGRES_DB: facilityvisit
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal
# NOTE, security favors removing external access from the database container
#      - external
#    ports:
#      - "5432:5432"

  db-init:
    image: va/facility-visit-flyway:latest
    # NOTE: These are the defaults from the flyway.conf   uncomment to override, esp for <secret-service-name> passwords
    #    environment:
    #      FLYWAY_URL: jdbc:postgresql://postgres1:5432/facilityvisit?user=facilityvisit_flyway&password=not-the-password
    #      FLYWAY_PLACEHOLDERS_USERNAME: facilityvisit_user
    #      FLYWAY_PLACEHOLDERS_SERVICENAME: facilityvisit_service
    #      FLYWAY_PLACEHOLDERS_ADMINNAME: facilityvisit_admin
    #      FLYWAY_PLACEHOLDERS_DBNAME: facilityvisit
    #      FLYWAY_PLACEHOLDERS_SCHEMANAME: facilityvisit
    #      FLYWAY_PLACEHOLDERS_USERPASSWORD: also-not-the-user-password
    #      FLYWAY_PLACEHOLDERS_SERVICEPASSWORD: also-not-the-service-password
    #      FLYWAY_PLACEHOLDERS_ADMINPASSWORD: also-not-the-admin-password
    depends_on:
      - postgres1
    networks:
      - internal

  opa-init:
    image: va/facility-visit-opa-init:latest
    depends_on:
      - opa
    networks:
      - internal

  facility-visit:
    image: va/facility-visit-app:latest
    hostname: facility-visit
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      POSTGRES_HOST: postgres1
      POSTGRES_DBNAME: facilityvisit
      POSTGRES_USER: facilityvisit_service
      POSTGRES_PASSWORD: also-not-the-service-password
      JAVA_PROFILE: "-Dspring.profiles.include=compose"
    volumes:
      - ${PWD}/app/src/docker/mock-mpi-server.keystore:/opt/va/mock-mpi-client.keystore
      - ${PWD}/app/src/docker/mock-mpi-server.truststore:/opt/va/mock-mpi-client.truststore
    depends_on:
      - postgres1
      - db-init
    networks:
      - internal
      - external

  jaeger:
    image: jaegertracing/all-in-one:1.20
    hostname: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT : "9411"
    networks:
      - internal
      - external

  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      - internal

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_HOST_NAME: kafka #192.168.99.100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
      - external
